export const PLAN_TRABAJO_COLUMNS = [
  {
    name: 'numero',
    label: 'Orden',
    field: 'numero',
    align: 'center',
    style: 'width: 5%',
    headerStyle: 'width: 5%',
  },
  {
    name: 'actividad',
    label: 'Actividad',
    field: 'actividad',
    align: 'left',
    style: 'width: 20%',
    headerStyle: 'width: 20%',
  },
  {
    name: 'descripcion',
    label: 'Descripción',
    field: 'descripcion',
    align: 'left',
    style: 'width: 30%',
    headerStyle: 'width: 30%',
  },
  {
    name: 'horaInicio',
    label: 'Hora inicio',
    field: 'horaInicio',
    align: 'center',
    style: 'width: 9%',
    headerStyle: 'width: 9%',
  },
  {
    name: 'horaFin',
    label: 'Hora fin',
    field: 'horaFin',
    align: 'center',
    style: 'width: 9%',
    headerStyle: 'width: 9%',
  },
  {
    name: 'duracion',
    label: 'Duración',
    field: 'duracion',
    align: 'center',
    style: 'width: 9%',
    headerStyle: 'width: 9%',
  },
  {
    name: 'lugar',
    label: 'Lugar',
    field: 'lugar',
    align: 'left',
    style: 'width: 10%',
    headerStyle: 'width: 10%',
  },
  {
    name: 'opciones',
    label: 'Opciones',
    field: 'opciones',
    align: 'center',
    style: 'width: 8%',
    headerStyle: 'width: 8%',
  },
]
